# Generated by Django 5.2.8 on 2025-11-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类别描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据类别',
                'verbose_name_plural': '数据类别',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=100, verbose_name='数据名字')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('data_value', models.JSONField(verbose_name='数据内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='records.category', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '数据记录',
                'verbose_name_plural': '数据记录',
                'ordering': ['-record_date', 'data_name'],
                'unique_together': {('data_name', 'record_date')},
            },
        ),
    ]
