# Generated by Django 5.2.8 on 2025-11-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='data_value',
            field=models.JSONField(default=dict, verbose_name='数据内容'),
        ),
    ]
