# Generated by Django 5.2.8 on 2025-11-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_datarecord_data_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('hit_number', models.IntegerField(verbose_name='命中数字')),
                ('hit_time', models.TimeField(verbose_name='命中时间')),
                ('opened_number', models.CharField(max_length=50, verbose_name='开出数字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日数字记录',
                'verbose_name_plural': '每日数字记录',
                'ordering': ['-date'],
            },
        ),
    ]
