# Generated by Django 5.2.8 on 2025-11-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_dailynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynumber',
            name='parsed_numbers',
            field=models.JSONField(blank=True, default=list, verbose_name='解析后的数字'),
        ),
    ]
