# Generated by Django 5.2.8 on 2025-11-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_dailynumber_parsed_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynumber',
            name='hit_number',
            field=models.CharField(max_length=255, verbose_name='命中数字'),
        ),
    ]
