# Generated by Django 5.2.8 on 2025-11-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_dailynumber_hit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynumber',
            name='opened_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='开出数字'),
        ),
    ]
