# Generated by Django 5.2.8 on 2025-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_dailynumber_opened_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynumber',
            name='parsed_numbers',
            field=models.JSONField(blank=True, null=True, verbose_name='解析后的数字'),
        ),
    ]
