# Generated by Django 5.2.8 on 2025-11-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_dailynumber_parsed_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='data_value',
            field=models.TextField(blank=True, null=True, verbose_name='数据内容'),
        ),
    ]
