# Generated by Django 5.2.8 on 2025-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_datarecord_data_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='parsed_numbers',
            field=models.JSONField(blank=True, null=True, verbose_name='解析后的数字'),
        ),
    ]
