# Generated by Django 5.2.8 on 2025-11-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_datarecord_parsed_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='is_excluded_group',
            field=models.BooleanField(default=False, verbose_name='是否属于被排除的组'),
        ),
    ]
