# Generated by Django 5.2.8 on 2025-11-19 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_datarecord_is_excluded_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today, verbose_name='记录日期'),
        ),
    ]
