# Generated by Django 5.2.8 on 2025-11-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_datarecord_record_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datarecord',
            unique_together={('category', 'data_name', 'record_date')},
        ),
    ]
