# Generated by Django 5.2.8 on 2025-11-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_datarecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datarecord',
            unique_together={('category', 'record_date')},
        ),
    ]
