# Generated by Django 5.0.1 on 2025-11-26 07:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_datarecord_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='网站名称')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='网站URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='网站描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据来源网站',
                'verbose_name_plural': '数据来源网站',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='datarecord',
            options={'ordering': ['-start_date', 'data_name'], 'verbose_name': '数据记录', 'verbose_name_plural': '数据记录'},
        ),
        migrations.AlterUniqueTogether(
            name='datarecord',
            unique_together={('category', 'data_name', 'start_date')},
        ),
        migrations.AddField(
            model_name='datarecord',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='category',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='records.website', verbose_name='数据来源网站'),
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='record_date',
        ),
    ]
