# Generated by Django 5.0.1 on 2025-11-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_website_alter_datarecord_options_and_more'),
    ]

    operations = [
        # 先删除可能存在的冲突索引
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS records_datarecord_category_id_a8d90f60 ON records_datarecord;',
            reverse_sql='CREATE INDEX records_datarecord_category_id_a8d90f60 ON records_datarecord(category_id);'
        ),
        # 重新添加正确的唯一约束
        migrations.AlterUniqueTogether(
            name='datarecord',
            unique_together={('category', 'data_name', 'start_date')},
        ),
    ]