# Generated by Django 5.0.1 on 2025-11-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_fix_unique_constraint'),
    ]

    operations = [
        # 这个迁移文件只是为了更新Django的迁移历史
        # 实际的数据库更改已经通过直接SQL执行
        migrations.RunSQL(
            sql='-- 索引和约束已通过直接SQL更新',
            reverse_sql='-- 回滚操作需要手动执行'
        ),
    ]