# Generated by Django 5.0.1 on 2025-11-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_add_website_id_to_category'),
    ]

    operations = [
    ]
